export const ALL_ALAT_BERATS_REQUEST = 'ALL_ALAT_BERATS_REQUEST'
export const ALL_ALAT_BERATS_SUCCESS = 'ALL_ALAT_BERATS_SUCCESS'
export const ALL_ALAT_BERATS_FAIL = 'ALL_ALAT_BERATS_FAIL'

export const NEW_ALAT_BERAT_REQUEST = 'NEW_ALAT_BERAT_REQUEST'
export const NEW_ALAT_BERAT_SUCCESS = 'NEW_ALAT_BERAT_SUCCESS'
export const NEW_ALAT_BERAT_RESET = 'NEW_ALAT_BERAT_RESET'
export const NEW_ALAT_BERAT_FAIL = 'NEW_ALAT_BERAT_FAIL'

export const DELETE_ALAT_BERAT_REQUEST = 'DELETE_ALAT_BERAT_REQUEST'
export const DELETE_ALAT_BERAT_SUCCESS = 'DELETE_ALAT_BERAT_SUCCESS'
export const DELETE_ALAT_BERAT_RESET = 'DELETE_ALAT_BERAT_RESET'
export const DELETE_ALAT_BERAT_FAIL = 'DELETE_ALAT_BERAT_FAIL'

export const UPDATE_ALAT_BERAT_REQUEST = 'UPDATE_ALAT_BERAT_REQUEST'
export const UPDATE_ALAT_BERAT_SUCCESS = 'UPDATE_ALAT_BERAT_SUCCESS'
export const UPDATE_ALAT_BERAT_RESET = 'UPDATE_ALAT_BERAT_RESET'
export const UPDATE_ALAT_BERAT_FAIL = 'UPDATE_ALAT_BERAT_FAIL'

export const ALAT_BERAT_DETAILS_REQUEST = 'SEE_ALAT_BERAT_REQUEST'
export const ALAT_BERAT_DETAILS_SUCCESS = 'SEE_ALAT_BERAT_SUCCESS'
export const ALAT_BERAT_DETAILS_FAIL = 'SEE_ALAT_BERAT_FAIL'

///export const SEE_ALAT_BERAT_REQUEST = 'SEE_ALAT_BERAT_REQUEST'
//export const SEE_ALAT_BERAT_SUCCESS = 'SEE_ALAT_BERAT_SUCCESS'
//export const SEE_ALAT_BERAT_FAIL = 'SEE_ALAT_BERAT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'